sudo: required
language: objective-c
osx_image: xcode9.4.1
rvm:
- 2.5.1
cache:
  timeout: 86400 # 1 day
  directories:
  - /home/travis/cache/
  - /home/travis/.rvm/
before_install:
- chmod a+x ./CI/travis/Unity_install.sh
- chmod a+x ./CI/travis/Unity_EditorTests.sh
install:
- ./CI/travis/Unity_install.sh
script:
- ./CI/travis/Unity_EditorTests.sh